import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { client } from '../utils/shopify'
import { addProductToCart } from "../utils/Cart";
import Router from "next/router";
import { getCart } from "../utils/Cart";


export default function Home({products}) {
  console.log( {products} )
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {products.map(product => {
        const addToCart = async () => {
          try {
            
            console.log("Fired");
            const variantId = product.variants[0].id
            addProductToCart([
              {
                variantId,
                quantity: 1,
              },
            ]);
          } catch (e) {
            console.log(e);
          }
        }
        
        const checkOut = async () => {
          const { webUrl } = await getCart();
          Router.replace(webUrl);
        }

        // addToCart()

        return (
          
          <div>
            <h1>{product.title}</h1>
            <p>{product.description}</p>
            <p>{product.variants[0].price}</p>
            <Image
              src={product.images[0].src}
              alt="Picture of the author"
              width={500}
              height={500}
            />
            {/* <div onClick: addToCart > */}
            <div>

            <button  onClick={addToCart}>
              Add to cart
            </button>
            <button onClick={checkOut}>
              Checkout
            </button>
            </div>
            {/* </div> */}

          </div>
            
          )
        })
      }
    </div>
  );
}


export async function getServerSideProps() {
  // Fetch data from external API
  const products = await client.product.fetchAll();

  // Pass data to the page via props
  return { props: { products: JSON.parse(JSON.stringify(products)) }};
}


